spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: sandi
    url: jdbc:mysql://localhost:3306/jpa
    password: sandeep@MCA1986
  jpa: show-sql:yes
  hibernate: ddl-auto:create

